### ISSUE TITLE
Is there a method to import scanpy DPT result to R diffusionmap

### ISSUE THREAD

**Issue by zacharylau10** [theislab/destiny#12]
Hi,
    I noticed that destiny function `DiffusionMap` is slow when import large scale single cell rna seq data, however the scanpy`sc.tl.diffmap` is speedup when treat the same data. 
    so I wonder whether there is a way to transport the scanpy `sc.tl.diffmap` results to R as the same structure as `DiffusionMap`. Thank you~

**Comment by flying-sheep** [comment]
which dataset? DiffusionMap should be pretty fast.

I’ll see what I can do and if I can’t speed it up, I’ll think about importing, OK?

**Comment by flying-sheep** [comment]
There’s now quite some progress in https://github.com/theislab/anndata2ri and https://github.com/LuckyMD/Code_snippets/blob/master/Seurat_to_anndata.ipynb!
