### ISSUE TITLE
Heatmap of genes along pseudotime 

### ISSUE THREAD

**Issue by tkapello** [theislab/destiny#20]
Hi,

 I would like to plot a heatmap of the expressed genes along the pseudotime generated by Diffusion Maps. I understand that there is no current function for that, is this correct? Do you have any suggestions?

Theo

**Comment by flying-sheep** [comment]
Sure! Use [`pt[cell, ]`](https://theislab.github.io/destiny/reference/DPT-matrix-methods.html) to get a vector of DPT values starting from `cell`, then use the `order()` of those values to reorder your data for the heatmap:

```r
dpt_order <- order(pt[cell, ])
heatmap(data[dpt_order, ])
```
