### ISSUE TITLE
Different results each time- set seed?

### ISSUE THREAD

**Issue by krc3004** [theislab/destiny#28]
Hi, 

I'm trying to use destiny in R and am computing the diffusion map using the dm function with k = 120 on a dataset of roughly 1000 cells.  However, the resulting diffusion map looks different every time I compute it, even with the same K.  I tried set.seed(100) before running dm but the results are still different.  Is there a way to ensure that the diffusion map looks the same every time, or perhaps is there a way to estimate how unstable the data/results are?  Thanks!

**Comment by flying-sheep** [comment]
Please use the version from git master! It works reproducibly.
