### ISSUE TITLE
Error creating DiffusionMap

### ISSUE THREAD

**Issue by swokybio** [theislab/destiny#29]
Hi,

I am trying to make a DiffusionMap in an integrated single cell object (SingleCellExperiment) created in Seurat and I am getting the following error:

```r
> dm <- DiffusionMap(t(pseudotime_sce))
Error in dataset_extract_doublematrix(data, vars) : 
  Data needs to be matrix, data.frame, ExpressionSet, or SingleCellExperiment
```

When I check the object class it is on dgCMatrix format:

```r
> class (pseudotime_sce)
[1] "dgCMatrix"
attr(,"package")
[1] "Matrix"
```

I've tried to convert the object to data.frame format using "as.data.frame" but had no success. 

Any thoughts?

**Comment by flying-sheep** [comment]
Well, you’re passing `t(pseudotime_sce)`. What’s `class(t(pseudotime_sce))`?

**Comment by apal6** [comment]
Same error, I treid to do the exact same thing 

`deng <- logcounts(deng_SCE)
colnames(deng) <- cellLabels
dm <- DiffusionMap(t(deng))`

error: dm <- DiffusionMap(t(deng))
Error in dataset_extract_doublematrix(data, vars) : 
  Data needs to be matrix, data.frame, ExpressionSet, or SingleCellExperiment
  
 Now I just tried to run the diffusion map on the SingleCellExperiment. 
 
Not sure why it is not mentioned in the vignette?

Thanks,
Aastha

**Comment by flying-sheep** [comment]
The [API reference](https://theislab.github.io/destiny/reference/DiffusionMap-class.html) says what `DiffusionMap` expects:

> The provided data can be a double [matrix](https://rdrr.io/r/base/matrix.html) of expression data or a [data.frame](https://rdrr.io/r/base/data.frame.html) with all non-integer (double) columns being treated as expression data features (and the others ignored), an ExpressionSet, or a [SingleCellExperiment](https://rdrr.io/pkg/SingleCellExperiment/man/SingleCellExperiment.html).
