### ISSUE TITLE
Plotting different conditions on the same diffusion components

### ISSUE THREAD

**Issue by Kensei-K** [theislab/destiny#36]
Hi! 

I've started to use destiny to analyze sc-RNAseq data where I have WT and a treated sample, and I'm expecting that the treatment will affect the developmental trajectories. 

I've used the same set of genes to perform diffusionMap on WT and the treated sample. And I see difference there. 

But is there a way to project the treated sample onto diffusion components calculated based on the WT as a reference, for more of a direct comparison?

Thank you in advance!

**Comment by flying-sheep** [comment]
You mean like here? https://github.com/theislab/destiny/issues/31#issuecomment-654951132

**Comment by Kensei-K** [comment]
No. 

dm_predict does exactly what I wanted to do! I found your answer in one of the other posts. 

Thanks!
