### ISSUE TITLE
Some cluster labels are missing after plotting the diffusion map 

### ISSUE THREAD

**Issue by aditisk** [theislab/destiny#37]
Hi,

I converted my Seurat Object to an SCE object and ran the DiffusionMap() function. When I plot the diffusion map, I'm missing the 1st and last cluster according to the Seurat cluster labels (UMAP and diffusion plots attached here). How can I fix this problem ?

Thank you.
![diffusion_plot](https://user-images.githubusercontent.com/15878219/88831387-453e4180-d19d-11ea-9a32-3cbbb0795d75.png)
![UMAP](https://user-images.githubusercontent.com/15878219/88831388-466f6e80-d19d-11ea-8647-e98dc2c9650f.png)

**Comment by flying-sheep** [comment]
There should be warnings in the console about the `palette()` not being big enough to show everything.

I have code to replace the default palette with a better one, which somehow doesn’t seem to run for you.

https://github.com/theislab/destiny/blob/28307e9d5dd755a79a84c2f9049cdd4a2112eacb/R/aaa.r#L17-L19

What R version do you have? Will it work if you manually do `palette(destiny:::gud_default_palette)`?

**Comment by aditisk** [comment]
Hi @flying-sheep, I didn't get any warnings. I set the palette manually but now I seem to have another problem. I am unable to reproduce the 3D plot any more despite of using plot(dm,1:3). It gives me the same result as using plot(dm,1:2). 

I'm using R version 3.6.3 
 
![DC1_DC2_plot](https://user-images.githubusercontent.com/15878219/88839074-7ec87a00-d1a8-11ea-98d9-7548f26e40a5.png)

**Comment by flying-sheep** [comment]
Sorry, but that’s impossible, you must be doing something differently. The code for `plot.DiffusionMap` never reassigns its `dims` argument, and if there’s 3 dimensions:

https://github.com/theislab/destiny/blob/28307e9d5dd755a79a84c2f9049cdd4a2112eacb/R/diffusionmap-plotting.r#L165

it uses the scatterplot3d function:

https://github.com/theislab/destiny/blob/28307e9d5dd755a79a84c2f9049cdd4a2112eacb/R/diffusionmap-plotting.r#L191-L194

try using `plot.Diffusionmap(dm, 1:3)` manually, maybe somehow `plot` dispatches the wrong function???
