### ISSUE TITLE
cannot install destiny

### ISSUE THREAD

**Issue by liuweihanty** [theislab/destiny#38]
Hi, thanks for developing the tool! I encounter such error when I install destiny using 

if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("destiny")

The error message is:
Show in New WindowClear OutputExpand/Collapse Output
Bioconductor version 3.11 (BiocManager 1.30.10), R 4.0.2 (2020-06-22)
Installing package(s) 'destiny'
cannot open URL 'https://bioconductor.org/packages/3.11/data/annotation/bin/macosx/contrib/4.0/PACKAGES.rds': HTTP status was '404 Not Found'cannot open URL 'https://bioconductor.org/packages/3.11/data/annotation/bin/macosx/contrib/4.0/PACKAGES.gz': HTTP status was '404 Not Found'cannot open URL 'https://bioconductor.org/packages/3.11/data/experiment/bin/macosx/contrib/4.0/PACKAGES.rds': HTTP status was '404 Not Found'cannot open URL 'https://bioconductor.org/packages/3.11/data/experiment/bin/macosx/contrib/4.0/PACKAGES.gz': HTTP status was '404 Not Found'cannot open URL 'https://bioconductor.org/packages/3.11/workflows/bin/macosx/contrib/4.0/PACKAGES.rds': HTTP status was '404 Not Found'cannot open URL 'https://bioconductor.org/packages/3.11/workflows/bin/macosx/contrib/4.0/PACKAGES.gz': HTTP status was '404 Not Found'Package which is only available in source form, and may need compilation of C/C++/Fortran: ‘destiny’

I've scratched my head and googling but couldn't figure out, do you know what is the issue? Thanks very much!

**Comment by flying-sheep** [comment]
Googling pretty quickly leads to this. Maybe you can help there if it doesn’t fix it for you. That’s a pretty generic problem and I’m just one person!

**Comment by Kensei-K** [comment]
Thank you! 

It worked after downloading some packages related to XCode since I'm a Mac user
