### ISSUE TITLE
Non-deterministic behaviour with set.seed()

### ISSUE THREAD

**Issue by MikeDMorgan** [theislab/destiny#5]
When using destiny for either diffusion map creation, or diffusion pseudo time inference, it is not possible to have a reproducible result, even when set.seed(N) is used in R.  I assume this is due to a random number generator or initialization outside of R, or that set.seed(NULL) is being set within the destiny package that overrides the user-set seed.

**Comment by flying-sheep** [comment]
Yeah, exactly. I traced this back to ARPACK’s FORTRAN code (via igraph::arpack)

Sadly calling into FORTRAN from C is so alien and low-level that I can’t really find where I could do something here. I found scipy/scipy#9023 which talks about this problem: Apparently the v0 parameter can be set, but they don’t have an idea how to properly set it.

Alternatives: There’s also the rARPACK binding (which might do something about the seed thing) and a discussion in igraph about replacing ARPACK: https://github.com/igraph/igraph/issues/551

**Comment by flying-sheep** [comment]
I think the clearest way forward is yixuan/RSpectra#14

**Comment by flying-sheep** [comment]
Fixed in b4e8dade4972ed5f3b815a58fd87c7244214cd09!

**Comment by wyattmcdonnell** [comment]
Hey @flying-sheep do you know if [b4e8dad](https://github.com/theislab/destiny/commit/b4e8dade4972ed5f3b815a58fd87c7244214cd09) has made its way to Bioconductor yet? Thanks!

**Comment by flying-sheep** [comment]
it didn’t, should be in the next release
