### ISSUE TITLE
Please make sure BioConductior web page of destiny provides link to source tarball

### ISSUE THREAD

**Issue by tillea** [theislab/destiny#51]
Hi,
the Debian R packaging team is currently upgrading all BioConductor packages.  When doing so I stumbled upon the page of [destiny](https://bioconductor.org/packages/release/bioc/html/destiny.html)  In contrast to all other BioConductor packages (at least those we are packaging for Debian) and also the previous versions of destiny the link

    Source Package

is not provided.  I'm perfectly aware that I can obtain the source code from here.  However, we are generating most of the packaging stuff for BioConductor packages automatically and a missing link breaks things and forces us to do manual work.
It would be really great if you could provide this link.
Thanks a lot in advance.
PS: I've written this issue to Philipp Angerer via [mail](https://lists.debian.org/debian-r/2021/09/msg00042.html) but his mail address is bouncing.  So please also update the maintainer address on the BioConductor page.

**Comment by nileshpatra** [comment]
CC: @flying-sheep 

This is now very urgent for us, since this is stalling the entire migration for us. Please, consider to process this as soon as possible.
Thanks for your work!

**Comment by flying-sheep** [comment]
All fixed now.
