### ISSUE TITLE
can destiny use by provid a distance matrix?

### ISSUE THREAD

**Issue by Mpaperlee** [theislab/destiny#58]
I have a distance matrix, create by self define method. And I want to use it in destiny. Could I do that?

**Comment by flying-sheep** [comment]
Yes, see the documentation: https://theislab.github.io/destiny/reference/DiffusionMap-class.html

You can do `DiffusionMap(distances = your_distmatrix)` or `DiffusionMap(covariate_dataframe, distances = your_distmatrix)`
