### ISSUE TITLE
density::DiffusionMap,Error: (converted from warning) 'as(<dsCMatrix>, "dsTMatrix")'

### ISSUE THREAD

**Issue by younng367** [theislab/destiny#67]
When i use density::DiffusionMap(x,),it always pop erro.
"Error: (converted from warning) 'as(<dsCMatrix>, "dsTMatrix")' is deprecated.
Use 'as(., "TsparseMatrix")' instead.
See help("Deprecated") and help("Matrix-deprecated")."
Evene i installed the developed vesion,cause i earlier thought that it might be my version problem!!!!!!

**Comment by danakrs** [comment]
> When i use density::DiffusionMap(x,),it always pop erro. "Error: (converted from warning) 'as(, "dsTMatrix")' is deprecated. Use 'as(., "TsparseMatrix")' instead. See help("Deprecated") and help("Matrix-deprecated")." Evene i installed the developed vesion,cause i earlier thought that it might be my version problem!!!!!!

I have the same error - any update on this one?

**Comment by flying-sheep** [comment]
You have set `options(warn=2)` to convert errors to warnings. So stop doing that. (`options(warn=0)` is the default)

The upcoming version has it fixed, too!
